//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class dbMyBlogEntities : DbContext
{
    public dbMyBlogEntities()
        : base("name=dbMyBlogEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<BlogContributor> BlogContributors { get; set; }
    public DbSet<BlogEntry> BlogEntries { get; set; }
    public DbSet<FeedEntry> FeedEntries { get; set; }
}
