//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class BlogContributor
{
    public BlogContributor()
    {
        this.BlogEntries = new HashSet<BlogEntry>();
        this.FeedEntries = new HashSet<FeedEntry>();
    }

    public int ID { get; set; }
    public string OwnerName { get; set; }
    public string OwnerURL { get; set; }
    public string UserGroup { get; set; }
    public string OwnerImageURL { get; set; }

    public virtual ICollection<BlogEntry> BlogEntries { get; set; }
    public virtual ICollection<FeedEntry> FeedEntries { get; set; }
}

public partial class BlogEntry
{
    public int ID { get; set; }
    public System.DateTime CreatedDateTime { get; set; }
    public System.DateTime ModifiedDateTime { get; set; }
    public string Title { get; set; }
    public string Summary { get; set; }
    public string URL { get; set; }
    public string Keywords { get; set; }
    public string BodyText { get; set; }
    public bool CommentsEnabled { get; set; }
    public bool Publish { get; set; }
    public int OwnerID { get; set; }
    public string TextFilePointer { get; set; }

    public virtual BlogContributor BlogContributor { get; set; }
}

public partial class FeedEntry
{
    public int ID { get; set; }
    public System.DateTime CreatedDateTime { get; set; }
    public System.DateTime ModifiedDateTime { get; set; }
    public string FeedText { get; set; }
    public int OwnerID { get; set; }

    public virtual BlogContributor BlogContributor { get; set; }
}
